2020-10-26 23:03:38,792 (77145/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-26 23:03:38,793 (77145/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-26 23:03:38,797 (77145/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2020-10-26 23:08:52,869 (77213/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-26 23:08:52,869 (77213/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-26 23:08:56,493 (77213/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "123456" does not exist\n\n'
2020-10-26 23:09:00,158 (77227/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-26 23:09:00,158 (77227/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-26 23:09:06,839 (77227/MainThread) pgcli.pgexecute ERROR - sql: 'ls -al', error: SyntaxError('syntax error at or near "ls"\nLINE 1: ls -al\n        ^\n')
2020-10-26 23:09:06,840 (77227/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "ls"\nLINE 1: ls -al\n        ^\n\n'
2020-10-26 23:09:16,488 (77227/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2020-10-26 23:09:16,488 (77227/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2020-10-26 23:10:05,628 (77227/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-26 23:10:05,631 (77227/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-26 23:10:09,011 (77227/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-26 23:10:09,012 (77227/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-26 23:10:13,628 (77227/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-26 23:10:13,628 (77227/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-26 23:10:18,469 (77227/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2020-10-26 23:10:18,472 (77227/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2020-10-26 23:36:28,839 (78210/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-26 23:36:28,840 (78210/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-26 23:38:10,973 (78290/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-26 23:38:10,973 (78290/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-26 23:41:03,939 (78374/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-26 23:41:03,940 (78374/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-26 23:47:20,047 (78532/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-26 23:47:20,048 (78532/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-26 23:47:20,053 (78532/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2020-10-26 23:48:02,277 (78548/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-26 23:48:02,278 (78548/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-26 23:48:02,282 (78548/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: invalid integer value "5432][" for connection option "port"\n\n'
2020-10-26 23:49:08,318 (78596/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-26 23:49:08,319 (78596/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-26 23:49:08,414 (78596/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "postgres]" does not exist\n\n'
2020-10-26 23:49:14,083 (78614/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-26 23:49:14,084 (78614/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-27 00:05:02,239 (78614/MainThread) pgcli.pgexecute ERROR - sql: 'desc student', error: SyntaxError('syntax error at or near "desc"\nLINE 1: desc student\n        ^\n')
2020-10-27 00:05:02,239 (78614/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "desc"\nLINE 1: desc student\n        ^\n\n'
2020-10-27 20:17:51,265 (82958/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-27 20:17:51,266 (82958/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-27 20:20:47,655 (83012/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-27 20:20:47,656 (83012/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-27 20:28:51,243 (83091/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-27 20:28:51,244 (83091/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-27 20:34:07,539 (83091/MainThread) pgcli.pgexecute ERROR - sql: '\\', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\\n        ^\n')
2020-10-27 20:34:07,542 (83091/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\\n        ^\n\n'
2020-10-27 20:34:17,307 (83091/MainThread) pgcli.pgexecute ERROR - sql: 'drop table public.u', error: UndefinedTable('table "u" does not exist\n')
2020-10-27 20:34:17,307 (83091/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: table "u" does not exist\n\n'
2020-11-05 02:16:16,697 (36667/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-05 02:16:16,698 (36667/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-11-05 02:18:59,554 (36667/MainThread) pgcli.pgexecute ERROR - sql: '\\', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\\n        ^\n')
2020-11-05 02:18:59,555 (36667/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\\n        ^\n\n'
2020-11-05 02:20:18,068 (36718/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-05 02:20:18,069 (36718/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-11-11 22:57:00,079 (36718/MainThread) pgcli.pgexecute ERROR - sql: '\\dt', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-11-11 22:57:00,088 (36718/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/dbcommands.py", line 311, in list_tables\n    return list_objects(cur, pattern, verbose, [\'r\', \'p\', \'\'])\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/dbcommands.py", line 302, in list_objects\n    cur.execute(sql)\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-11-11 22:57:00,089 (36718/MainThread) pgcli.main ERROR - sql: '\\dt', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-11-11 22:57:00,090 (36718/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 634, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 880, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/dbcommands.py", line 311, in list_tables\n    return list_objects(cur, pattern, verbose, [\'r\', \'p\', \'\'])\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/dbcommands.py", line 302, in list_objects\n    cur.execute(sql)\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2021-01-14 21:12:01,333 (26027/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-01-14 21:12:01,334 (26027/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-14 21:12:29,596 (26483/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-01-14 21:12:29,596 (26483/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-14 21:12:31,288 (26483/MainThread) pgcli.pgexecute ERROR - sql: 'll', error: SyntaxError('syntax error at or near "ll"\nLINE 1: ll\n        ^\n')
2021-01-14 21:12:31,289 (26483/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "ll"\nLINE 1: ll\n        ^\n\n'
2021-01-14 21:18:55,084 (26483/MainThread) pgcli.pgexecute ERROR - sql: 'create table pinche', error: SyntaxError('syntax error at end of input\nLINE 1: create table pinche\n                           ^\n')
2021-01-14 21:18:55,084 (26483/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: create table pinche\n                           ^\n\n'
2021-01-14 21:18:58,218 (26483/MainThread) pgcli.pgexecute ERROR - sql: 'create table pinche  \\', error: SyntaxError('syntax error at or near "\\"\nLINE 1: create table pinche  \\\n                             ^\n')
2021-01-14 21:18:58,219 (26483/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: create table pinche  \\\n                             ^\n\n'
2021-01-14 21:19:00,879 (26483/MainThread) pgcli.pgexecute ERROR - sql: 'create table pinche  \\', error: SyntaxError('syntax error at or near "\\"\nLINE 1: create table pinche  \\\n                             ^\n')
2021-01-14 21:19:00,880 (26483/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: create table pinche  \\\n                             ^\n\n'
2021-01-14 21:20:18,958 (26483/MainThread) pgcli.pgexecute ERROR - sql: 'create table pinche\n(\nRoomId VARCHAR(30),\nStartPos varchar(100),\nEndPos varchar(100),\n)\n', error: SyntaxError('syntax error at or near ")"\nLINE 6: )\n        ^\n')
2021-01-14 21:20:18,959 (26483/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near ")"\nLINE 6: )\n        ^\n\n'
2021-01-14 21:20:23,716 (26483/MainThread) pgcli.pgexecute ERROR - sql: 'create table pinche\n(\nRoomId VARCHAR(30),\nStartPos varchar(100),\nEndPos varchar(100),\n)', error: SyntaxError('syntax error at or near ")"\nLINE 6: )\n        ^\n')
2021-01-14 21:20:23,716 (26483/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near ")"\nLINE 6: )\n        ^\n\n'
2021-01-14 23:44:17,970 (8575/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-01-14 23:44:17,971 (8575/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-14 23:56:36,662 (16612/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-01-14 23:56:36,663 (16612/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-15 00:10:19,524 (25992/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-01-15 00:10:19,526 (25992/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-15 00:11:14,687 (25992/MainThread) pgcli.pgexecute ERROR - sql: '\\sf', error: InvalidName("invalid name syntax\nLINE 1: SELECT ''::pg_catalog.regproc::pg_catalog.oid\n               ^\n")
2021-01-15 00:11:14,691 (25992/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/dbcommands.py", line 1615, in show_function_definition\n    cur.execute(sql)\npsycopg2.errors.InvalidName: invalid name syntax\nLINE 1: SELECT \'\'::pg_catalog.regproc::pg_catalog.oid\n               ^\n\n'
2021-03-05 00:44:27,922 (96499/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-05 00:44:27,923 (96499/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-05 00:44:27,990 (96499/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not translate host name "pgm-2zea0bdddasr91507o.pg.rds.aliyuncs.com" to address: nodename nor servname provided, or not known\n\n'
2021-03-05 01:16:53,830 (11827/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-05 01:16:53,831 (11827/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-05 01:16:53,840 (11827/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-03-05 01:16:58,456 (11900/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-05 01:16:58,456 (11900/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-05 01:17:00,491 (11900/MainThread) pgcli.pgexecute ERROR - sql: 'll', error: SyntaxError('syntax error at or near "ll"\nLINE 1: ll\n        ^\n')
2021-03-05 01:17:00,492 (11900/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "ll"\nLINE 1: ll\n        ^\n\n'
2021-03-05 01:17:01,386 (11900/MainThread) pgcli.pgexecute ERROR - sql: '\\s', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\s\n        ^\n')
2021-03-05 01:17:01,387 (11900/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\s\n        ^\n\n'
2021-03-05 01:17:22,425 (11900/MainThread) pgcli.pgexecute ERROR - sql: '\\t', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\t\n        ^\n')
2021-03-05 01:17:22,426 (11900/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\t\n        ^\n\n'
2021-03-05 01:17:25,789 (11900/MainThread) pgcli.pgexecute ERROR - sql: '\\dd', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\dd\n        ^\n')
2021-03-05 01:17:25,790 (11900/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\dd\n        ^\n\n'
2021-03-05 01:18:18,370 (11900/MainThread) pgcli.pgexecute ERROR - sql: '\\sf', error: InvalidName("invalid name syntax\nLINE 1: SELECT ''::pg_catalog.regproc::pg_catalog.oid\n               ^\n")
2021-03-05 01:18:18,374 (11900/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/dbcommands.py", line 1615, in show_function_definition\n    cur.execute(sql)\npsycopg2.errors.InvalidName: invalid name syntax\nLINE 1: SELECT \'\'::pg_catalog.regproc::pg_catalog.oid\n               ^\n\n'
2021-03-05 01:22:33,842 (11900/MainThread) pgcli.pgexecute ERROR - sql: '\\n s carpools 1 100', error: SyntaxError('LIMIT #,# syntax is not supported\nLINE 1: select * from carpools limit 1,100\n                               ^\nHINT:  Use separate LIMIT and OFFSET clauses.\n')
2021-03-05 01:22:33,844 (11900/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/iocommands.py", line 203, in execute_named_query\n    cur.execute(query)\npsycopg2.errors.SyntaxError: LIMIT #,# syntax is not supported\nLINE 1: select * from carpools limit 1,100\n                               ^\nHINT:  Use separate LIMIT and OFFSET clauses.\n\n'
2021-03-05 01:35:18,408 (11900/MainThread) pgcli.main ERROR - sql: '\\n sall', error: Exception('Bad arguments\nmissing substitution for $1 in query:\n  select * from $1')
2021-03-05 01:35:18,412 (11900/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 634, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 880, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/iocommands.py", line 202, in execute_named_query\n    raise Exception("Bad arguments\\n" + params)\nException: Bad arguments\nmissing substitution for $1 in query:\n  select * from $1\n'
2021-03-05 21:02:58,088 (8279/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-05 21:02:58,089 (8279/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-05 21:04:18,404 (8279/MainThread) pgcli.pgexecute ERROR - sql: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad', error: SyntaxError('syntax error at or near "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad"\nLINE 1: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...\n        ^\n')
2021-03-05 21:04:18,407 (8279/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad"\nLINE 1: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...\n        ^\n\n'
2021-03-05 21:08:49,028 (8279/MainThread) pgcli.pgexecute ERROR - sql: 'jjjjsadaaaaaadad', error: SyntaxError('syntax error at or near "jjjjsadaaaaaadad"\nLINE 1: jjjjsadaaaaaadad\n        ^\n')
2021-03-05 21:08:49,029 (8279/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "jjjjsadaaaaaadad"\nLINE 1: jjjjsadaaaaaadad\n        ^\n\n'
2021-03-06 13:13:26,434 (87376/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 13:13:26,435 (87376/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 13:13:26,445 (87376/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n\n'
2021-03-06 13:15:22,159 (88377/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 13:15:22,160 (88377/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 13:15:22,554 (88377/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2021-03-06 13:15:26,846 (88451/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 13:15:26,847 (88451/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 13:15:26,855 (88451/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2021-03-06 13:16:05,554 (88760/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 13:16:05,555 (88760/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 13:37:34,053 (99911/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 13:37:34,054 (99911/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 13:45:23,676 (4578/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 13:45:23,677 (4578/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 13:45:46,247 (4767/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 13:45:46,247 (4767/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 13:45:46,302 (4767/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "testdb" does not exist\n\n'
2021-03-06 13:47:33,336 (6000/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 13:47:33,337 (6000/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 13:48:37,111 (6757/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 13:48:37,112 (6757/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 14:19:05,891 (23763/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 14:19:05,892 (23763/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 14:20:42,797 (24819/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 14:20:42,798 (24819/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 21:50:52,449 (94461/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-06 21:50:52,450 (94461/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-06 22:17:56,567 (94461/MainThread) pgcli.pgexecute ERROR - sql: '\\n sa carpools', error: UndefinedTable('relation "carpools" does not exist\nLINE 1: select * from carpools\n                      ^\n')
2021-03-06 22:17:56,572 (94461/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/iocommands.py", line 203, in execute_named_query\n    cur.execute(query)\npsycopg2.errors.UndefinedTable: relation "carpools" does not exist\nLINE 1: select * from carpools\n                      ^\n\n'
2021-03-07 17:47:25,868 (94461/MainThread) pgcli.main ERROR - sql: '\\n sa carpools\\', error: ValueError('No escaped character')
2021-03-07 17:47:25,875 (94461/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 634, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 880, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/iocommands.py", line 189, in execute_named_query\n    params = shlex.split(pattern)\n  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 311, in split\n    return list(lex)\n  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 300, in __next__\n    token = self.get_token()\n  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 109, in get_token\n    raw = self.read_token()\n  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 210, in read_token\n    raise ValueError("No escaped character")\nValueError: No escaped character\n'
2021-03-07 17:47:26,699 (94461/MainThread) pgcli.main ERROR - sql: '\\n sa carpools\\', error: ValueError('No escaped character')
2021-03-07 17:47:26,699 (94461/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 634, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 880, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgspecial/iocommands.py", line 189, in execute_named_query\n    params = shlex.split(pattern)\n  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 311, in split\n    return list(lex)\n  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 300, in __next__\n    token = self.get_token()\n  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 109, in get_token\n    raw = self.read_token()\n  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 210, in read_token\n    raise ValueError("No escaped character")\nValueError: No escaped character\n'
2021-03-10 00:41:19,663 (86088/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-03-10 00:41:19,665 (86088/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
